### ISSUE TITLE
Contribute backend for the project

### ISSUE THREAD

**Issue by shreyanshiitb** [desiredeveloper/Indian-Kabaadiya#1]
#hacktoberfest
All you need is to set up a database for this website to get the orders for waste pickup. You may use any open source DB or google firebase.

**Comment by AldoRG** [comment]
I made a branch and I added mongodb and express server to use a db, also I made some routes to save some test data and display it in the main page, I couldnt upload the branch because I dont have access to, if you're interested to see it let me know. Regards!

**Comment by shreyanshiitb** [comment]
@AldoRG 
I have sent you an invite to become the collaborator. Also you can raise a pull request to get it approved by me.
